name: Games
version: ${project.version}
main: me.ollie.games.Games
api-version: 1.16
authors: [ Ollie ]
description: Bunch of Games Plugin Time
depend:
  - Citizens

commands:
  game:
    description: Main command
  test:
    description: Testing commands
